export const chineseBookNames: Record<string, string> = {
  Genesis: "創世記",
  Exodus: "出埃及記",
  Leviticus: "利未記",
  Numbers: "民數記",
  Deuteronomy: "申命記",
  Joshua: "約書亞記",
  Judges: "士師記",
  Ruth: "路得記",
  "I Samuel": "撒母耳記上",
  "II Samuel": "撒母耳記下",
  "1 Samuel": "撒母耳記上",
  "2 Samuel": "撒母耳記下",
  "I Kings": "列王紀上",
  "II Kings": "列王紀下",
  "1 Kings": "列王紀上",
  "2 Kings": "列王紀下",
  "I Chronicles": "歷代志上",
  "II Chronicles": "歷代志下",
  "1 Chronicles": "歷代志上",
  "2 Chronicles": "歷代志下",
  Ezra: "以斯拉記",
  Nehemiah: "尼希米記",
  Esther: "以斯帖記",
  Job: "約伯記",
  Psalms: "詩篇",
  Proverbs: "箴言",
  Ecclesiastes: "傳道書",
  "Song of Solomon": "雅歌",
  Isaiah: "以賽亞書",
  Jeremiah: "耶利米書",
  Lamentations: "耶利米哀歌",
  Ezekiel: "以西結書",
  Daniel: "但以理書",
  Hosea: "何西阿書",
  Joel: "約珥書",
  Amos: "阿摩司書",
  Obadiah: "俄巴底亞書",
  Jonah: "約拿書",
  Micah: "彌迦書",
  Nahum: "那鴻書",
  Habakkuk: "哈巴谷書",
  Zephaniah: "西番雅書",
  Haggai: "哈該書",
  Zechariah: "撒迦利亞書",
  Malachi: "瑪拉基書",
  Matthew: "馬太福音",
  Mark: "馬可福音",
  Luke: "路加福音",
  John: "約翰福音",
  Acts: "使徒行傳",
  Romans: "羅馬書",
  "I Corinthians": "哥林多前書",
  "II Corinthians": "哥林多後書",
  "1 Corinthians": "哥林多前書",
  "2 Corinthians": "哥林多後書",
  Galatians: "加拉太書",
  Ephesians: "以弗所書",
  Philippians: "腓立比書",
  Colossians: "歌羅西書",
  "I Thessalonians": "帖撒羅尼迦前書",
  "II Thessalonians": "帖撒羅尼迦後書",
  "1 Thessalonians": "帖撒羅尼迦前書",
  "2 Thessalonians": "帖撒羅尼迦後書",
  "I Timothy": "提摩太前書",
  "II Timothy": "提摩太後書",
  "1 Timothy": "提摩太前書",
  "2 Timothy": "提摩太後書",
  Titus: "提多書",
  Philemon: "腓利門書",
  Hebrews: "希伯來書",
  James: "雅各書",
  "I Peter": "彼得前書",
  "II Peter": "彼得後書",
  "1 Peter": "彼得前書",
  "2 Peter": "彼得後書",
  "I John": "約翰一書",
  "II John": "約翰二書",
  "III John": "約翰三書",
  "1 John": "約翰一書",
  "2 John": "約翰二書",
  "3 John": "約翰三書",
  Jude: "猶大書",
  Revelation: "啟示錄",
  "Revelation of John": "啟示錄",
};

export function displayBookName(book: string) {
  const normalized = book
    .replace(/^I /, "1 ")
    .replace(/^II /, "2 ")
    .replace(/^III /, "3 ")
    .replace(/^IV /, "4 ");
  return chineseBookNames[book] ?? chineseBookNames[normalized] ?? book;
}
